### ISSUE TITLE
Broken Pages (NavBar, the whole blog itself), and checklist for changess

### ISSUE THREAD

**Issue by NormalFery** [NormalFery/normalfery.github.io#1]
Pretty much *EVERY* blog webpage in [the site](https://normalfery.github.io) is pretty much broken entirely starting from Blog 5 onwards due to un-implemented changes from the CSS into them

![Broken Blog 6](https://github.com/user-attachments/assets/18579bb7-f106-404e-a270-1546246441ed)

The issue will track pretty much every webpage fixed starting from blog 5+ 

TODO :
- [X] Start Flexbox implementation
- [X] Fix broken pages
- [x] Fix color schemes for certain pages (unreadable / hard to read)
- [x] Complete Flexbox implementation

Broken pages TODO : 

- [X] Blog 5
- [X] Blog 6
- [X] Blog 7
- [X] Blog 8
- [X] Blog 9
- [X] Blog 10
- [X] Blog 11
- [X] Blog 12
- [X] Blog 13
- [X] Blog 14
- [X] Blog 15
- [X] Blog 16
- [X] Blog 17

Color scheme changes : 
- [x] style3.css (Thoughts) > Revise link colors, still dark
- [x] style2.css (Memories) > Revise colors in general, seems very light completely

Check to implement : 
- [ ] Dropdown menus?

**Comment by NormalFery** [comment]
Updated to include #2 changes thanks to @Clancy-boyo  (thanks cutie)

**Comment by NormalFery** [comment]
Updated to include changes made in https://github.com/NormalFery/normalfery.github.io/commit/3747d2ba69d2d36f99a61f68dd5fd0e020ccb4c1

**Comment by NormalFery** [comment]
Commit 03979ef added Dropdown menus, this issue is (finally) Complete !
